apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: argocd
  
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
status:
  loadBalancer: {}